### PR TITLE
Allows to pass node objects as lightbox contents

### PR DESCRIPTION
**Pull request by funkyfuture**
as proposed in #15. i tested it with both input types in my use-case.

### CODE REVIEW

**Comment by electerious** [comment]
Thanks for the PR. I will take a closer look at it by time.

**Comment by Coriou** [comment]
Interested in the feature too ! Tested for my basic use case and it's working great

**Comment by Coriou** [comment]
Thanks for the update @electerious

**Comment by electerious** [comment]
basicLightbox v5 is out and includes node elements and templates in `.create()`. Check out all the examples. It's very powerful and yet super simple to use. Thanks for the suggestion!

https://github.com/electerious/basicLightbox/blob/master/CHANGELOG.md#500---2018-09-23

**Pull request closed without merging**
